import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Load the Dataset
df = pd.read_csv("india_covid_sample_data.csv")
df['date'] = pd.to_datetime(df['date'])
# Basic Data Check
print(df.head())
print(df.info())
# Visualization 1: Daily New COVID Cases (Line Chart)
plt.figure()
plt.plot(df['date'], df['new_cases'])
plt.title("Daily New COVID-19 Cases in India")
plt.xlabel("Date")
plt.ylabel("New Cases")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# Visualization 2: Daily Deaths in India (Bar Chart)
plt.figure()
plt.bar(df['date'], df['new_deaths'])
plt.title("Daily COVID-19 Deaths in India")
plt.xlabel("Date")
plt.ylabel("New Deaths")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# Visualization 3: Cumulative Total Cases (Area Chart)
plt.figure()
plt.fill_between(df['date'], df['total_cases'], alpha=0.6)
plt.title("Cumulative COVID-19 Cases in India")
plt.xlabel("Date")
plt.ylabel("Total Cases")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# Visualization 4: Cumulative Total Deaths (Line Chart)
plt.figure()
plt.plot(df['date'], df['total_deaths'])
plt.title("Cumulative COVID-19 Deaths in India")
plt.xlabel("Date")
plt.ylabel("Total Deaths")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# Visualization 5: 7-Day Moving Average (Trend Analysis)
df['death_7day_avg'] = df['new_deaths'].rolling(window=7).mean()

plt.figure()
plt.plot(df['date'], df['death_7day_avg'])
plt.title("7-Day Moving Average of COVID-19 Deaths (India)")
plt.xlabel("Date")
plt.ylabel("Average Deaths")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# KPI Calculations (For Dashboard Cards)
total_cases = df['total_cases'].iloc[-1]
total_deaths = df['total_deaths'].iloc[-1]
peak_deaths = df['new_deaths'].max()
peak_date = df.loc[df['new_deaths'].idxmax(), 'date']

print("Total Cases:", total_cases)
print("Total Deaths:", total_deaths)
print("Peak Daily Deaths:", peak_deaths)
print("Peak Death Date:", peak_date)
# Key Insight Code 
print(f"Highest number of deaths ({peak_deaths}) occurred on {peak_date.date()}")
